### ISSUE TITLE
Slugify not found while running fronted.py

### ISSUE THREAD

**Issue by carlos-mg89** [waymarkedtrails/waymarked-trails-site#305]
So, I have been following the Installation tutorial (this one https://github.com/waymarkedtrails/waymarked-trails-site/wiki/Installation ) to set up a local copy of the Waymarked Trails project in my machine. However, I'm stuck on the last step of it.

After I run `WMT_CONFIG=hiking ./frontend.py`, I get the followin error:

```
Traceback (most recent call last):
  File "./frontend.py", line 32, in <module>
    from api.routes import RoutesApi
  File "/home/carlos/workspace/waymarked-trails-site/api/routes.py", line 24, in <module>
    import api.details
  File "/home/carlos/workspace/waymarked-trails-site/api/details.py", line 28, in <module>
    from slugify import slugify
ModuleNotFoundError: No module named 'slugify'
```

I tried installing the slugify (`pip install python-slugify` and even `pip install slugify` just in case) package without any luck.

Actually, for me, the API access is the most important part, I don't care that much that the frontend works.

Any help would be very appreciated. I'm not that fluent with Python, but I do understand that the package is missing while trying to import it. But I do have it installed. I read that Python uses environments, and while checking the code I see something related to it, but I don't know exactly what to do. And it seems I followed correctly the instructions step by step.

Thanks in advance!

**Comment by carlos-mg89** [comment]
Same error happens with the Docker tutorial: https://github.com/waymarkedtrails/waymarked-trails-docker :(

**Comment by carlos-mg89** [comment]
Solved it! The issue is that my default python being used was the 2.7. I executed `python3 -m pip install python-slugify` and now it worked!
